[build]
  command = "pip install jupyter-book==2.1.5 jupytext==1.19.3 beautifulsoup4==4.15.0 && make dropdown && make build"
  publish = "jupyter-book/_build/html"

[build.environment]
  PYTHON_VERSION = "3.13"