[build]
  command = "pip install jupyter-book==1.0.4.post1 jupytext==1.16.7 beautifulsoup4==4.13.3 'sphinx>=7,<8' && make dropdown && make"
  publish = "jupyter-book/_build/html"

[build.environment]
  PYTHON_VERSION = "3.13"