name: pseudotemporal
channels:
  - conda-forge
  - r
dependencies:
  - conda-forge::python=3.9.15
  - conda-forge::r-base=4.2.2
  - conda-forge::scanpy=1.9.1
  - conda-forge::jupyterlab=3.5.0
  - bioconda::scvelo=0.2.5
  - pip:
      - anndata2ri==1.1
      - rpy2==3.5.3
      - session_info
