name: clustering
channels:
  - defaults
  - conda-forge
dependencies:
  - conda-forge::python=3.8.12
  - conda-forge::scanpy=1.9.1
  - conda-forge::anndata=0.8.0
  - pip:
      - umap-learn==0.5.2
      - leidenalg>=0.8.3
      - igraph>=0.9.8
      - session_info
