name: bp-integration
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - anndata=0.8.0
  - anndata2ri=1.1
  - bbknn=1.5.1
  - bioconductor-singlecellexperiment=1.16.0
  - igraph=0.10.2
  - jupyterlab=3.5.0
  - numpy=1.23.4
  - pandas=1.5.1
  - pip=22.3
  - python=3.9.13
  - python-igraph=0.10.2
  - r-base=4.1.3
  - r-sessioninfo=1.2.2
  - r-seurat=4.2.0
  - r-spatstat=2.3_4
  - rpy2=3.5.1
  - scanpy=1.9.1
  - scikit-learn=1.1.3
  - scikit-misc=0.1.4
  - scipy=1.9.3
  - scvi-tools=0.18.0
  - session-info=1.0.0
  - umap-learn=0.5.3
  - pip:
      - scib==1.0.4
