name: perturbation_modeling
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::python=3.9.15
  - conda-forge::scanpy=1.9.1
  - conda-forge::jupyterlab=3.5.0
  - pip:
      - scgen==2.1.0
      - pertpy==0.2.0
      - session_info
