name: Build book

on: [push, pull_request]

concurrency: preview-${{ github.ref }}

env:
  PREVIEW_BRANCH: gh-pages

jobs:
  build-book:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Setup environment
        run: |
          pip install uv
          uv pip install --system "jupyter-book==1.0.4.post1" jupytext beautifulsoup4

      - name: Cache jupyter-cache folder
        uses: actions/cache@v4
        env:
          cache-name: jupyter-cache
        with:
          path: jupyter-book/_build/.jupyter_cache
          key: v1-${{ github.ref }}-${{ hashFiles('notebook_scripts/**/*.py') }}
          restore-keys: |
            v1-${{ github.ref }}-${{ hashFiles('notebook_scripts/**/*.py') }}
            v1-${{ github.ref }}
            v1-refs/heads/master

      - name: Insert dropdowns to all chapters
        run: make dropdown

      - name: Build the JupyterBook
        run: make

  pdfhtml:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade uv
          uv pip install --system jupyter-book==1.0.4.post1 jupytext beautifulsoup4 playwright

      - name: Install Playwright browsers
        run: playwright install --with-deps

      - name: Install Headless Chrome dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -yq $(cat .github/workflows/pyppeteer_requirements.txt)

      - name: Install Chromium
        run: uv pip install --system pyppeteer

      - name: Build PDF from HTML (Docs)
        run: make pdf

      - uses: actions/upload-artifact@v7
        with:
          name: PDF_HTML
          path: jupyter-book/_build/pdf/book.pdf
