name: advanced-integration
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::python=3.9.15
  - conda-forge::scanpy=1.9.1
  - conda-forge::r-base=4.1.3
  - conda-forge::r-seurat=4.1.1
  - conda-forge::r-remotes
  - conda-forge::r-devtools
  - bioconda::bioconductor-singlecellexperiment
  - conda-forge::notebook
  - conda-forge::rpy2=3.5.6
  - bioconda::anndata2ri=1.1
  - conda-forge::r-spatstat.core
  - conda-forge::pip
  - pip:
      - scvi-tools==0.19.0
      - multigrate==0.0.2
      - scglue==0.3.2
